import os
import re
from datetime import date, datetime, timedelta

from jinja2 import Environment, FileSystemLoader, select_autoescape

_HERE = os.path.dirname(__file__)
TEMPLATES_DIR = os.path.join(_HERE, "..", "templates")
DOCS_DIR = os.path.join(_HERE, "..", "docs")

_env = Environment(
    loader=FileSystemLoader(TEMPLATES_DIR),
    autoescape=select_autoescape(["html"]),
)

# Kindle's browser can't reliably load custom web fonts, and with no JavaScript
# there is nowhere to remember what the reader picked: CSS cannot carry state
# across a page load. So every presentation choice is baked into its own static
# page, identified by a filename suffix. Choosing one is following a link, and
# every link on that page points at the matching variant — which is what makes
# the choice survive a page turn instead of snapping back to the default.
#
# Suffixes compose as <family><size> and both defaults are empty, so
# serif + medium keeps the plain "index.html" / "<slug>.html" names that
# existing bookmarks and already-generated archive pages point at.
FAMILIES = {
    "serif": {"suffix": "", "label": "襯線", "css": 'Georgia, "Times New Roman", serif'},
    "sans": {"suffix": "-sans", "label": "無襯線", "css": "Helvetica, Arial, sans-serif"},
}

# `scale` stretches conf["article_page_lines"] — which is tuned for the medium
# size — so every size still fits about one e-ink screen: bigger text, fewer
# paragraphs per page.
SIZES = {
    "small": {"suffix": "-s", "label": "小", "px": 16, "scale": 20 / 16},
    "medium": {"suffix": "", "label": "中", "px": 20, "scale": 1.0},
    "large": {"suffix": "-l", "label": "大", "px": 26, "scale": 20 / 26},
}

SIZE_ORDER = ["small", "medium", "large"]
DEFAULT_FAMILY = "serif"
DEFAULT_SIZE = "medium"

# Every (family, size) pair, i.e. every static page written per logical page.
VARIANTS = [(family, size) for family in FAMILIES for size in SIZE_ORDER]

# One shared stylesheet instead of re-inlining the same ~2.5 KB in every file.
# That was over half of a typical article page and was re-downloaded on every
# page turn; it is also what keeps the variant pages affordable, since all a
# variant needs in its own HTML is a body class.
STYLESHEET = "style.css"


# Dated copies of the two companion pages live in their own directories, so
# each day's deep read and each week's roundup survives the next run instead of
# being overwritten by it. The rolling docs/deepread.html and docs/weekly.html
# stay put as "the latest one" — that's what the front page links to.
DEEPREAD_DIR = "deepread"
WEEKLY_DIR = "weekly"


def _other_family(family: str) -> str:
    return "sans" if family == "serif" else "serif"


def _with_suffix(html_name: str, family: str, size: str = DEFAULT_SIZE) -> str:
    suffix = FAMILIES[family]["suffix"] + SIZES[size]["suffix"]
    if not suffix:
        return html_name
    return html_name[: -len(".html")] + suffix + ".html"


def page_exists(html_name: str) -> bool:
    """True when a docs/ page has already been generated by an earlier run.

    Only the default variant is checked: a renderer always writes the whole set
    of variants or none of them, and checking just one keeps the answer stable
    across a change to the variant table (during which the other variants of an
    older page legitimately don't exist yet).
    """
    return os.path.exists(os.path.join(DOCS_DIR, _with_suffix(html_name, DEFAULT_FAMILY)))


def _variant_href(base_name: str, family: str, size: str, up: str = "") -> str | None:
    """Link to `base_name` in this variant, or None when that file isn't there.

    Used for the front page's links to the quiz / deep read / weekly pages: a
    feature switched off in config, or one that has never produced a page,
    should not leave a link pointing at nothing.
    """
    name = _with_suffix(base_name, family, size)
    return name if os.path.exists(os.path.join(DOCS_DIR, f"{up}{name}")) else None


def _existing_variant(dir_path: str, base_name: str, family: str, size: str) -> str:
    """`base_name` in the best variant actually on disk, preferring the exact one.

    Pages written before a variant existed only have the older variants saved,
    so linking a two-month-old archived day from a newly added size would 404.
    Those links fall back to the copy that is really there — same day, nearest
    presentation — and newer days, written in every variant, match exactly.
    """
    for f, s in ((family, size), (family, DEFAULT_SIZE), (DEFAULT_FAMILY, DEFAULT_SIZE)):
        name = _with_suffix(base_name, f, s)
        if os.path.exists(os.path.join(dir_path, name)):
            return name
    return _with_suffix(base_name, family, size)


def _prefs(base_name: str, family: str, size: str) -> dict:
    """Switcher links for a page whose variants all share one file name."""
    other = _other_family(family)
    return {
        "family": family,
        "size": size,
        "size_links": [
            (SIZES[s]["label"], _with_suffix(base_name, family, s), s == size)
            for s in SIZE_ORDER
        ],
        "family_href": _with_suffix(base_name, other, size),
        "family_label": FAMILIES[other]["label"],
    }


def _archive_dir() -> str:
    d = os.path.join(DOCS_DIR, "archive")
    os.makedirs(d, exist_ok=True)
    return d


def _article_dir() -> str:
    d = os.path.join(DOCS_DIR, "article")
    os.makedirs(d, exist_ok=True)
    return d


def _dated_dir(name: str) -> str:
    d = os.path.join(DOCS_DIR, name)
    os.makedirs(d, exist_ok=True)
    return d


def _parse_date(name: str):
    try:
        return datetime.strptime(name, "%Y-%m-%d").date()
    except ValueError:
        return None


def _dated_page_dates(dir_name: str) -> list:
    """Canonical (suffix-free) dates of the dated pages under docs/<dir_name>/."""
    d = os.path.join(DOCS_DIR, dir_name)
    if not os.path.isdir(d):
        return []
    dates = []
    for f in os.listdir(d):
        if not f.endswith(".html"):
            continue
        name = f[: -len(".html")]
        if _parse_date(name):
            dates.append(name)
    return sorted(dates)


def _split_paragraphs(text: str) -> list:
    return [line.strip() for line in text.splitlines() if line.strip()]


_CJK_RE = re.compile(r"[぀-ヿ㐀-䶿一-鿿豈-﫿]")
_LATIN_WORD_RE = re.compile(r"[A-Za-z0-9]+")


def _paragraph_lines(text: str) -> float:
    """Estimate how many on-screen lines a paragraph occupies, script-aware.

    Roughly ~32 full-width CJK glyphs or ~12 Latin words fit on one line at the
    medium size; used only to decide page breaks, so a coarse estimate is fine.
    """
    cjk = len(_CJK_RE.findall(text))
    latin_words = len(_LATIN_WORD_RE.findall(text))
    return max(1.0, cjk / 32 + latin_words / 12)


def _paginate_paragraphs(paragraphs: list, lines_per_page: int) -> list:
    """Page boundaries as (start, end) index pairs into `paragraphs`.

    Paragraphs are never split mid-way, so each e-ink page turn lands on a clean
    paragraph boundary. A single over-long paragraph simply gets its own page.
    Index pairs rather than slices, because a reader switching text size has to
    be sent to whichever page of the new size holds the paragraph they were on.
    """
    if not paragraphs:
        return [(0, 0)]
    if lines_per_page <= 0:
        return [(0, len(paragraphs))]
    pages, start, used = [], 0, 0.0
    for i, para in enumerate(paragraphs):
        cost = _paragraph_lines(para) + 0.7  # + inter-paragraph spacing
        if i > start and used + cost > lines_per_page:
            pages.append((start, i))
            start, used = i, 0.0
        used += cost
    pages.append((start, len(paragraphs)))
    return pages


def _page_for_para(pages: list, para_index: int) -> int:
    """1-based page holding `para_index` in that size's pagination."""
    for n, (start, end) in enumerate(pages, 1):
        if start <= para_index < end:
            return n
    return len(pages)


def estimate_reading_minutes(text: str) -> int:
    """Rough minutes-to-read across CJK (per char) and Latin (per word) text."""
    if not text:
        return 0
    cjk = len(_CJK_RE.findall(text))
    latin_words = len(_LATIN_WORD_RE.findall(text))
    minutes = cjk / 350 + latin_words / 220
    return max(1, round(minutes))


def _existing_dates(exclude: str | None = None) -> list:
    """Canonical (suffix-free) dates only — variants share these dates."""
    dates = []
    for f in os.listdir(_archive_dir()):
        if not f.endswith(".html"):
            continue
        name = f[: -len(".html")]
        if name == exclude or not _parse_date(name):
            continue
        dates.append(name)
    return sorted(dates)


def _digest_title(date_str: str, language: str) -> str:
    return f"每日 AI 文摘 {date_str}" if language.startswith("zh") else f"Daily AI Digest {date_str}"


def render_stylesheet() -> None:
    """Write docs/style.css, shared by every page this run generates."""
    os.makedirs(DOCS_DIR, exist_ok=True)
    css = _env.get_template("style.css.j2").render(
        families=FAMILIES, sizes=SIZES, size_order=SIZE_ORDER
    )
    with open(os.path.join(DOCS_DIR, STYLESHEET), "w", encoding="utf-8") as f:
        f.write(css)


def render_digest(date_str: str, categories: dict, conf: dict, brief: str = "") -> None:
    prev_dates = _existing_dates(exclude=date_str)
    prev_base = f"{prev_dates[-1]}.html" if prev_dates else None

    # An archived day links to its own deep read when one was generated, so a
    # past day's digest and its companion piece stay connected.
    has_deep = page_exists(f"{DEEPREAD_DIR}/{date_str}.html")

    tmpl = _env.get_template("digest.html.j2")
    base_name = f"{date_str}.html"
    for family, size in VARIANTS:
        html = tmpl.render(
            title=_digest_title(date_str, conf["language"]),
            generated_at=date_str,
            categories=categories,
            brief=brief,
            lang=conf["language"],
            css_href=f"../{STYLESHEET}",
            home_href=_with_suffix("../index.html", family, size),
            archive_href=_with_suffix("index.html", family, size),
            deepread_href=(
                _with_suffix(f"../{DEEPREAD_DIR}/{date_str}.html", family, size)
                if has_deep
                else None
            ),
            prev_href=(
                _existing_variant(_archive_dir(), prev_base, family, size)
                if prev_base
                else None
            ),
            article_prefix="../article/",
            article_suffix=FAMILIES[family]["suffix"] + SIZES[size]["suffix"],
            **_prefs(base_name, family, size),
        )
        path = os.path.join(_archive_dir(), _with_suffix(base_name, family, size))
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)


def render_index(date_str: str, categories: dict, conf: dict, brief: str = "") -> None:
    os.makedirs(DOCS_DIR, exist_ok=True)
    tmpl = _env.get_template("digest.html.j2")
    for family, size in VARIANTS:
        html = tmpl.render(
            title=_digest_title(date_str, conf["language"]),
            generated_at=date_str,
            categories=categories,
            brief=brief,
            lang=conf["language"],
            css_href=STYLESHEET,
            home_href=None,
            archive_href=_with_suffix("archive/index.html", family, size),
            prev_href=None,
            article_prefix="article/",
            article_suffix=FAMILIES[family]["suffix"] + SIZES[size]["suffix"],
            quiz_href=_variant_href("quiz.html", family, size),
            deepread_href=_variant_href("deepread.html", family, size),
            weekly_href=_variant_href("weekly.html", family, size),
            **_prefs("index.html", family, size),
        )
        path = os.path.join(DOCS_DIR, _with_suffix("index.html", family, size))
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)


def _article_page_name(slug: str, page_no: int) -> str:
    """Page 1 keeps the bare {slug}.html so digest links stay stable; later
    pages get a -p{n} suffix. Both start with the date-prefixed slug, so the
    date-based pruning in prune_old_article_pages catches every page."""
    return f"{slug}.html" if page_no == 1 else f"{slug}-p{page_no}.html"


def render_articles(date_str: str, categories: dict, conf: dict) -> None:
    """Offline full-text pages per article, in every presentation variant.

    Long articles are split into several sequential pages (one physical HTML
    file each) so Kindle readers can turn pages — each turn is a full, clean
    e-ink refresh landing at the top — instead of scrolling a slow screen.
    Filenames are prefixed with the digest date so they can be pruned on the
    same schedule as the archive pages that link to them.

    Each text size paginates separately, so switching size is resolved by
    paragraph: the link goes to whichever page of the new size contains the
    paragraph the reader is currently looking at, rather than to the same page
    number, which would land somewhere else in the article.
    """
    tmpl = _env.get_template("article.html.j2")
    paginate = conf.get("paginate_articles", True)
    base_lines = conf.get("article_page_lines", 14)

    for articles in categories.values():
        for a in articles:
            slug = a.get("slug")
            if not slug:
                continue
            paragraphs = _split_paragraphs(a.get("full_text", ""))

            pagination = {}
            for size in SIZE_ORDER:
                if paginate and paragraphs:
                    lines = max(1, round(base_lines * SIZES[size]["scale"]))
                    pagination[size] = _paginate_paragraphs(paragraphs, lines)
                else:
                    pagination[size] = [(0, len(paragraphs))]

            for family in FAMILIES:
                other = _other_family(family)
                for size in SIZE_ORDER:
                    pages = pagination[size]
                    total = len(pages)
                    for idx, (start, end) in enumerate(pages):
                        page_no = idx + 1
                        is_last = page_no == total
                        base_name = _article_page_name(slug, page_no)
                        prev_base = (
                            _article_page_name(slug, page_no - 1) if page_no > 1 else None
                        )
                        next_base = (
                            _article_page_name(slug, page_no + 1) if not is_last else None
                        )
                        size_links = [
                            (
                                SIZES[s]["label"],
                                _with_suffix(
                                    _article_page_name(
                                        slug, _page_for_para(pagination[s], start)
                                    ),
                                    family,
                                    s,
                                ),
                                s == size,
                            )
                            for s in SIZE_ORDER
                        ]
                        html = tmpl.render(
                            title=a["title"],
                            lang=conf["language"],
                            source=a["source"],
                            original_link=a["link"],
                            paragraphs=paragraphs[start:end],
                            qa=a.get("qa") if is_last else None,
                            read_minutes=a.get("read_minutes") if page_no == 1 else None,
                            css_href=f"../{STYLESHEET}",
                            home_href=_with_suffix("../index.html", family, size),
                            archive_href=_with_suffix("../archive/index.html", family, size),
                            page_no=page_no,
                            page_total=total,
                            prev_href=(
                                _with_suffix(prev_base, family, size) if prev_base else None
                            ),
                            next_href=(
                                _with_suffix(next_base, family, size) if next_base else None
                            ),
                            family=family,
                            size=size,
                            size_links=size_links,
                            family_href=_with_suffix(base_name, other, size),
                            family_label=FAMILIES[other]["label"],
                        )
                        path = os.path.join(
                            _article_dir(), _with_suffix(base_name, family, size)
                        )
                        with open(path, "w", encoding="utf-8") as f:
                            f.write(html)


def _prune_dated_dir(path: str, retention_days: int) -> None:
    """Drop pages in `path` whose leading YYYY-MM-DD is older than the cutoff."""
    if not retention_days or retention_days <= 0:
        return
    if not os.path.isdir(path):
        return
    cutoff = date.today() - timedelta(days=retention_days)
    for fname in os.listdir(path):
        if not fname.endswith(".html"):
            continue
        try:
            file_date = datetime.strptime(fname[:10], "%Y-%m-%d").date()
        except ValueError:
            continue
        if file_date < cutoff:
            os.remove(os.path.join(path, fname))


def prune_old_article_pages(retention_days: int) -> None:
    _prune_dated_dir(_article_dir(), retention_days)


def prune_old_companion_pages(retention_days: int) -> None:
    """Dated deep-read and weekly-roundup pages, on the archive's schedule."""
    _prune_dated_dir(os.path.join(DOCS_DIR, DEEPREAD_DIR), retention_days)
    _prune_dated_dir(os.path.join(DOCS_DIR, WEEKLY_DIR), retention_days)


def prune_old_archives(retention_days: int) -> None:
    # The archive's index pages don't start with a date, so they're skipped.
    _prune_dated_dir(_archive_dir(), retention_days)


def render_quiz(quiz_items: list, source_date: str | None, conf: dict) -> None:
    """A single rolling recall-quiz page (docs/quiz.html) in every variant."""
    os.makedirs(DOCS_DIR, exist_ok=True)
    zh = conf["language"].startswith("zh")
    title = "昨日回顧小考" if zh else "Daily Recall Quiz"
    tmpl = _env.get_template("quiz.html.j2")
    for family, size in VARIANTS:
        html = tmpl.render(
            title=title,
            lang=conf["language"],
            quiz=quiz_items,
            source_date=source_date,
            css_href=STYLESHEET,
            home_href=_with_suffix("index.html", family, size),
            archive_href=_with_suffix("archive/index.html", family, size),
            **_prefs("quiz.html", family, size),
        )
        path = os.path.join(DOCS_DIR, _with_suffix("quiz.html", family, size))
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)


def render_weekly(roundup: dict | None, date_label: str, conf: dict, date_str: str = "") -> None:
    """The weekly roundup page, rolling and dated.

    Same split as the deep read: docs/weekly.html is the latest one, and a dated
    copy under docs/weekly/ keeps every past week's roundup around instead of
    letting the next one overwrite it.
    """
    os.makedirs(DOCS_DIR, exist_ok=True)
    zh = conf["language"].startswith("zh")
    title = "本週主題回顧" if zh else "This Week in Themes"
    tmpl = _env.get_template("weekly.html.j2")

    targets = [("", DOCS_DIR, "weekly.html")]
    if roundup and date_str:
        targets.append(("../", _dated_dir(WEEKLY_DIR), f"{date_str}.html"))

    for up, out_dir, base_name in targets:
        for family, size in VARIANTS:
            html = tmpl.render(
                title=title,
                lang=conf["language"],
                roundup=roundup,
                date_label=date_label,
                css_href=f"{up}{STYLESHEET}",
                home_href=_with_suffix(f"{up}index.html", family, size),
                archive_href=_with_suffix(f"{up}archive/index.html", family, size),
                **_prefs(base_name, family, size),
            )
            path = os.path.join(out_dir, _with_suffix(base_name, family, size))
            with open(path, "w", encoding="utf-8") as f:
                f.write(html)


def render_deep_read(deep: dict | None, article: dict | None, conf: dict, date_str: str = "") -> None:
    """The 'deep read of the day' page, rolling and dated.

    docs/deepread.html is the rolling copy the front page links to. When there
    is real content it is also written to docs/deepread/<date>.html, so the
    day's deep read — the most expensive thing the run generates — is still
    readable after tomorrow's run replaces the rolling copy.
    """
    os.makedirs(DOCS_DIR, exist_ok=True)
    zh = conf["language"].startswith("zh")
    title = "每日深讀" if zh else "Deep Read of the Day"
    tmpl = _env.get_template("deepread.html.j2")

    # (path prefix back to docs/, output directory, file name)
    targets = [("", DOCS_DIR, "deepread.html")]
    if deep and date_str:
        targets.append(("../", _dated_dir(DEEPREAD_DIR), f"{date_str}.html"))

    for up, out_dir, base_name in targets:
        for family, size in VARIANTS:
            article_href = None
            if article and article.get("slug"):
                article_href = _with_suffix(
                    f"{up}article/{article['slug']}.html", family, size
                )
            html = tmpl.render(
                title=title,
                lang=conf["language"],
                deep=deep,
                date_str=date_str,
                article_title=article["title"] if article else None,
                article_href=article_href,
                original_link=article["link"] if article else None,
                css_href=f"{up}{STYLESHEET}",
                home_href=_with_suffix(f"{up}index.html", family, size),
                archive_href=_with_suffix(f"{up}archive/index.html", family, size),
                digest_href=(
                    _with_suffix(f"{up}archive/{date_str}.html", family, size)
                    if date_str
                    else None
                ),
                **_prefs(base_name, family, size),
            )
            path = os.path.join(out_dir, _with_suffix(base_name, family, size))
            with open(path, "w", encoding="utf-8") as f:
                f.write(html)


def render_archive_index(conf: dict) -> None:
    dates = list(reversed(_existing_dates()))
    deep_dates = set(_dated_page_dates(DEEPREAD_DIR))
    weekly_dates = list(reversed(_dated_page_dates(WEEKLY_DIR)))
    tmpl = _env.get_template("archive_index.html.j2")
    for family, size in VARIANTS:
        deep_dir = os.path.join(DOCS_DIR, DEEPREAD_DIR)
        weekly_dir = os.path.join(DOCS_DIR, WEEKLY_DIR)
        date_links = [
            (
                d,
                _existing_variant(_archive_dir(), f"{d}.html", family, size),
                f"../{DEEPREAD_DIR}/{_existing_variant(deep_dir, f'{d}.html', family, size)}"
                if d in deep_dates
                else None,
            )
            for d in dates
        ]
        weekly_links = [
            (d, f"../{WEEKLY_DIR}/{_existing_variant(weekly_dir, f'{d}.html', family, size)}")
            for d in weekly_dates
        ]
        html = tmpl.render(
            title="文摘存檔" if conf["language"].startswith("zh") else "Digest Archive",
            lang=conf["language"],
            date_links=date_links,
            weekly_links=weekly_links,
            css_href=f"../{STYLESHEET}",
            # Last renderer of the run, so the front page's variants normally
            # already exist and this resolves exactly. On a housekeeping-only
            # run they may not have been written yet, and a link to the nearest
            # existing front page beats one that 404s.
            home_href=f"../{_existing_variant(DOCS_DIR, 'index.html', family, size)}",
            **_prefs("index.html", family, size),
        )
        path = os.path.join(_archive_dir(), _with_suffix("index.html", family, size))
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
